---
title: "Bonanza Hares Exploratory Report"
author: "Bri Baker"
date: "November 12, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
library(lubridate)

```


```{r import}
bonanza_hares <- read_csv(here("data" , "bonanza_hares.csv"))
```

# Introduction



# Data and Analysis



# Exploratory Findings


## Annual Juvenile Trap Counts

```{r}
annual_juvinile <- bonanza_hares %>% 
  filter(age == "j") %>% 
  mutate(year_new = as.numeric(year(mdy(date)))) %>% 
  count(year_new) %>% 
  rename(count = n)

ggplot(annual_juvinile, aes(year_new, count)) +
  geom_line() +
  scale_x_continuous("Year", breaks = seq(1999, 2012, 1)) +
  theme_light() +
  labs(title = "Figure 1: Annual Count of Juvinile Bonanza Hares" , 
       y = "Individuals (count)") +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))

```


## Juvenile Weights


## Juvenile Weight Comparison


## Juvenile Weight and Hind Foot Length


# Summary

# Citations


Kielland, K., F.S. Chapin, R.W. Ruess, and Bonanza Creek LTER. 2017. Snowshoe hare physical data in Bonanza Creek Experimental Forest: 1999-Present ver 22. Environmental Data Initiative. https://doi.org/10.6073/pasta/03dce4856d79b91557d8e6ce2cbcdc14

